<?php

/**
 * Copyright 2014 Centre NTE <http://nte.unifr.ch>, Université de Fribourg, Suisse
 * 
 * This file is part of Equal+.
 *
 * Equal+ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Equal+ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Equal+.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace NTE\EqualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EqualApprochesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EqualApprochesRepository extends EntityRepository
{
	public function getDimCheckbox($approche_id)
	{
		/*
		$dim = $this->findBy(
			array('id' => $approche_id))
		;*/
		
		$qb = $this->createQueryBuilder('a')
					->leftJoin('a.dimensions', 'd')
					->addSelect('d')
		;

		/*
		if (!$dim) {
			throw new NotFoundHttpException('La liste de dimensions est vide');
		}
		
    	return $dim->getDimensions();
		*/

		return $qb->getQuery()->getResult();
	}
}
