<?php

/**
 * Copyright 2014 Centre NTE <http://nte.unifr.ch>, Université de Fribourg, Suisse
 * 
 * This file is part of Equal+.
 *
 * Equal+ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Equal+ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Equal+.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace NTE\EqualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EqualItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EqualItemsRepository extends EntityRepository
{
	public function getItemsFromDim($dimension_id)
	{
		$qbb = $this->createQueryBuilder('i')
					->leftJoin('i.dimension', 'd', 'WITH', 'd.id = :dimension_id')
					->setParameter('dimension_id', $dimension_id)
		;

		$qb = $this->findBy(
			array('dimension' => $dimension_id))
		;

		return $qb;

		//return $qb->getQuery()->getResult();
	}
}
