<?php

/**
 * Copyright 2014 Centre NTE <http://nte.unifr.ch>, Université de Fribourg, Suisse
 * 
 * This file is part of Equal+.
 *
 * Equal+ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Equal+ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Equal+.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace NTE\EqualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EqualFeedbacksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EqualFeedbacksRepository extends EntityRepository
{
	public function getFeed($id_dim, $points, $nb_question)
	{
		$nb_question == 0 ? $moyenne = $points : $moyenne = $points/$nb_question;
/*
		$q = $this->createQuery(
			'SELECT f 
			FROM NTEEqualBundle:EqualFeedbacks f 
			WHERE f.dimension = :id_dim 
			AND :moyenne BETWEEN round(f.liminf, 1) 
			AND round(f.limsup, 1) 
			ORDER BY f.limsup ASC'
			)->setParameters(array(
				'id_dim' => $id_dim,
				'moyenne' => $moyenne));
*/
		$q = $this->createQueryBuilder('f')
				->where('f.dimension = :id_dim')
				->andWhere(':moyenne BETWEEN f.liminf AND f.limsup')
				->orderBy('f.limsup', 'ASC')
				->setParameters(array(
					'id_dim' => $id_dim,
					'moyenne' => $moyenne))
				->setFirstResult(0)
				->setMaxResults(1)
		;

		return $q->getQuery()->getResult();
	}
}
