<?php

namespace NTE\EqualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EqualResultatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EqualResultatsRepository extends EntityRepository
{
}
