<?php

namespace NTE\EqualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangueRepository extends EntityRepository
{
}
