<?php

/**
 * Copyright 2014 Centre NTE <http://nte.unifr.ch>, Université de Fribourg, Suisse
 * 
 * This file is part of Equal+.
 *
 * Equal+ is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Equal+ is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Equal+.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace NTE\EqualBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * PagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesRepository extends EntityRepository
{
	public function getPages($menu_id)
	{
		/*
		$pages = $this->createQueryBuilder('p')
		->leftJoin('p.title', 't')
		->addSelect('t')
		->leftJoin('p.text', 't')
		->addSelect('t')
		->orderBy('p.menu_id', 'ASC')
		->getQuery();
		*/

		$pages = $this->findBy(array('parent' => $menu_id));

		if (!$pages) {
			throw new NotFoundHttpException('Aucune page disponible');
		}

    	return $pages;

	}


	public function getSelectList()
	{
		$qb = $this->createQueryBuilder('a')
		->where('a.publication = 1');
    // Et on retourne simplement le QueryBuilder, et non la Query, attention
		return $qb;
	}
}
