nte_equal:
    resource: "@NTEEqualBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    requirements:
        _locale: fr|de|en
    prefix: /{_locale}/admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    requirements:
        _locale: fr|de|en
    prefix: /{_locale}/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    requirements:
        _locale: fr|de|en
    prefix: /{_locale}/admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
